version: 0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64
environment:
  GH_TOKEN:
    secure: IwxJFoU4Ghh0vpZ01KkZcyshnGooeBfL5hQhT9w5dJt9LDUX3qrhoPXYbwjhlB9G
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - choco install yarn --ignore-dependencies
  - git reset --hard HEAD
  - yarn
  - node --version

build_script:
  - yarn build

test: off
